### ISSUE TITLE
[bug]: Audio plays the surah from the beginning instead of starting from the requested verse

### ISSUE THREAD

**Issue by muben88** [quran/quran.com-frontend-next#1719] opened 2022-07-12 18:45 UTC
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When I open ayatul-kursi for example and I want to change the reciter, the audio start playing the surah from the beginning instead of playing the requested verse only.

### Steps to reproduce

1- Go to https://quran.com/ayatul-kursi
2- Play the audio
3- Change the reciter and play the audio
Now the audio will start from the beginning of the surah.

### Environment (please complete the following information) and Add any other context about this bug

OS: Windows
Browser: Chrome

### Environment

Production(quran.com)

**Comment by koshpendi** [comment] 2022-07-24 06:35
Assalamualaikum. I can hide audio player when reciter is changed. So user will click play button again. Lemme know if it OK. Inwa Allahu I'll contribute @muben88

**Comment by muben88** [comment] 2022-07-26 14:22
Wa alaikoum assalam brother. If it's working, try opening a PR & wait for approval.

**Comment by osamasayed** [comment] 2022-08-23 06:17
Alsalamu Alikum @muben88 , we have just had a production release that contains a fix for this issue, please check again and let me know if the issue is still there.

**Closed** 2022-08-29 12:15 UTC
Labels: bug
