### ISSUE TITLE
[feature]: Translation in reader view

### ISSUE THREAD

**Issue by circlePulse** [quran/quran.com-frontend-next#1644] opened 2022-05-13 03:22 UTC
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

Asalamualaykum,
Currently, there is no straightforward way to see an ayah-by-ayah translation in the reading view as the ayah is playing. Attached is an idea for one way to implement it.
Jazakumulahukhayran for all your hard work in developing this amazing website!

### Your purposed solution for this feature

![](https://canny.io/images/ccc1293ebab2fd31e025d7b6c316af92.jpg)
![b467795a56e1446aac196adf34cafd00](https://user-images.githubusercontent.com/80917157/168397818-792ed453-1da2-41c1-b29f-0c5865787680.jpg)
![fc1264a79bb9621916c29227095beb2d](https://user-images.githubusercontent.com/80917157/168397834-461df597-b40e-409c-a6fa-eb0762a81c92.jpg)

**Comment by osamasayed** [comment] 2022-08-20 09:44
Duplicate of #1740

**Closed by osamasayed** 2022-08-20 09:44 UTC
