### ISSUE TITLE
[bug]: Mac OS X Safari UI Bug

### ISSUE THREAD

**Issue by smali-kazmi** [quran/quran.com-frontend-next#1660] opened 2022-05-30 15:11 UTC
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

URL: https://quran.com/56

facing this issue on Mac OS X safari working fine in chrome

<img width="660" alt="image" src="https://user-images.githubusercontent.com/749977/171020318-0e01e0a2-f1a1-4f47-b6b2-4094d96cbf27.png">

### Steps to reproduce

1. Open Link https://quran.com/56 in Mac OS X  Safari Version 15.1 (17612.2.9.1.20) 
2. select reading tab

### Environment (please complete the following information) and Add any other context about this bug

Safari Version 15.1 (17612.2.9.1.20) 

### Environment

Production(quran.com)

**Comment by YousifAtique** [comment] 2022-06-10 15:46
Salam u alaikum wa rahmat ul Allah hi wa baraka tu hu

Followed the reproducing steps above and, unfortunately, can't reproduce. 

Following is what I see and all looks fine AFAICT. Although, I must admit that I tried reproducing this in Safari 15.3 (15612.4.9.18, 15612)

![image](https://user-images.githubusercontent.com/615306/173102374-c2ede370-4170-45bd-97ec-18d63e3e5c39.png)

**Comment by Ashraf-Ali-aa** [comment] 2022-06-25 15:55
it looks like its using the indopak font

**Comment by osamasayed** [comment] 2022-08-20 11:29
> [smali-kazmi](/smali-kazmi)

Alsalamu Alikum, can you check if the issue is still happening? I cannot reproduce it on my Mac's safari.

<img width="535" alt="Screen Shot 2022-08-20 at 6 28 51 PM" src="https://user-images.githubusercontent.com/15169499/185743882-ecf5cf81-0a73-43bc-8356-b7158d3e967a.png">

**Comment by osamasayed** [comment] 2022-10-24 14:38
Jazakum Allah Khairan everyone. Closing due to inactivity. Feel free to comment and will re-open if necessary.

**Comment by hazem3500** [comment] 2023-02-20 17:00
@osamasayed I believe you forgot to close the issue 😅

**Comment by osamasayed** [comment] 2023-02-22 11:40
> @osamasayed I believe you forgot to close the issue 😅

Yes I did. JAK for notifying me :)

**Closed by osamasayed** 2023-02-22 11:40 UTC
Labels: bug
