### ISSUE TITLE
[bug]: Tajweed font-size not updating

### ISSUE THREAD

**Issue by noypi** [quran/quran.com-frontend-next#1946] opened 2023-04-11 23:02 UTC
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Font size seems fixed for tajweed. It is not updating. It is too big for mobile.

![Screenshot_20230412_064231_org mozilla firefox](https://user-images.githubusercontent.com/337302/231306156-92f24596-605b-4f79-ade5-3ad340a8834b.jpg)

![Screenshot_20230412_064219_org mozilla firefox](https://user-images.githubusercontent.com/337302/231306168-69c6e1de-bf29-4d0d-aaaa-858fa4b5a1c0.jpg)

![Screenshot_20230412_064159_org mozilla firefox](https://user-images.githubusercontent.com/337302/231306172-80c7be5c-a120-478a-8d4d-2f3cf8ed7f94.jpg)

### Steps to reproduce

1. Set font to tajweed
2. Try to change font size

### Environment (please complete the following information) and Add any other context about this bug

OS: android
Browser: firefox
Version: 110.0.1

### Environment

Production(quran.com)

**Comment by SBenkara** [comment] 2023-04-23 17:01
@ThatSameer no it hasn't been fixed. In order to reproduce the bug you need to use Firefox, both Mobile and Web browsers have the bug. let me know if you're still unable to reproduce

**Comment by ThatSameer** [comment] 2023-04-23 18:13
@SBenkara You are correct - I was initially trying to set the Network Conditions in Chrome to simulate Firefox browser but that wasn't reproducing the bug. I am now seeing the bug on the actual Firefox browser 👍

I would like to work on this issue if that is ok.

**Comment by SBenkara** [comment] 2023-04-23 19:23
I can't assign issues, maybe @osamasayed  can help

**Comment by osamasayed** [comment] 2023-04-23 19:33
Jazakumu Allah Khairan @SofianeBenkara and @ThatSameer for your help. I assigned it to you @ThatSameer

**Closed** 2023-04-24 13:10 UTC
Labels: bug
