### ISSUE TITLE
create developers page

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend-next#8] opened 2020-05-11 04:55 UTC
design here: http://beta.quran.com/pages/developers

**Comment by Shemsedin** [comment] 2020-10-04 11:59
@mmahalwy will be takin this.

**Comment by mmahalwy** [comment] 2020-10-06 00:57
@Shemsedin please do!

**Comment by tifa2UP** [comment] 2020-10-21 17:42
@mmahalwy this is blocked by design, so I'm gonna close the issue until we have the new specs.

**Closed by tifa2UP** 2020-10-21 17:42 UTC
Labels: good first issue, help wanted
